# SPDX-License-Identifier: MIT
label W132D Linux v7.1 mainline
	kernel /Image
	fdt /rockchip/rk3528-w132d.dtb
	append root=@ROOT_DEVICE@ rootfstype=ext4 rw rootwait console=tty0 console=ttyS0,115200n8 earlycon=uart8250,mmio32,0xff9f0000 clk_ignore_unused pd_ignore_unused
