# SPDX-License-Identifier: MIT
label Armbian W132D
	kernel /Image
	fdt /rockchip/rk3528-w132d.dtb
	initrd /uInitrd
	append root=UUID=b921b045-1df0-41c3-af44-4c6f280d3fae rw rootwait console=ttyS0,115200n8 earlycon=uart8250,mmio32,0xff9f0000
